language: c
sudo: false

cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.cabal/packages
    - $HOME/.stack

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar

matrix:
  include:
    - env: STACK_RESOLVER=lts-8.0
      addons: {apt: {packages: [libgmp-dev]}}
    - env: STACK_RESOLVER=lts-7.18
      addons: {apt: {packages: [libgmp-dev]}}
    - env: GHCVER=8.0.1 CABALVER=1.24 CABAL_JOBS=-j2
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1], sources: [hvr-ghc]}}
    - env: GHCVER=7.6.3 CABALVER=1.16
      addons: {apt: {packages: [cabal-install-1.16,ghc-7.6.3], sources: [hvr-ghc]}}
    - env: DEBIANVER=wheezy GHCVER=7.4.1 CABALVER=1.16 NO_CABAL_CACHE=1 CABAL_FLAGS=--flags=ghc74-generic
      addons: {apt: {packages: [cabal-install-1.16,ghc-7.4.1], sources: [hvr-ghc]}}
    - env: STACK_RESOLVER=lts-6.29
      addons: {apt: {packages: [libgmp-dev]}}
    - env: GHCVER=7.10.3 CABALVER=1.22 CABAL_JOBS=-j2
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}
    - env: GHCVER=7.8.4 CABALVER=1.18 CABAL_JOBS=-j2
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: GHCVER=7.4.1 CABALVER=1.16 CABAL_FLAGS=--flags=ghc74-generic
      addons: {apt: {packages: [cabal-install-1.16,ghc-7.4.1], sources: [hvr-ghc]}}
    - env: GHCVER=7.4.2 CABALVER=1.16 CABAL_FLAGS=--flags=ghc74-generic
      addons: {apt: {packages: [cabal-install-1.16,ghc-7.4.2], sources: [hvr-ghc]}}
    - env: GHCVER=7.6.1 CABALVER=1.16
      addons: {apt: {packages: [cabal-install-1.16,ghc-7.6.1], sources: [hvr-ghc]}}
    - env: GHCVER=7.6.2 CABALVER=1.16
      addons: {apt: {packages: [cabal-install-1.16,ghc-7.6.2], sources: [hvr-ghc]}}
    - env: GHCVER=7.8.1 CABALVER=1.18 CABAL_JOBS=-j2
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.1], sources: [hvr-ghc]}}
    - env: GHCVER=7.8.2 CABALVER=1.18 CABAL_JOBS=-j2
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.2], sources: [hvr-ghc]}}
    - env: GHCVER=7.8.3 CABALVER=1.18 CABAL_JOBS=-j2
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.3], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.1 CABALVER=1.22
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.2 CABALVER=1.22
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2], sources: [hvr-ghc]}}

before_install:
 ## - cat /proc/cpuinfo
 - if [ x"$STACK_RESOLVER" != x ];
   then
     ./travis-CI/stack/before-install.sh ;
     export PATH=$HOME/.local/bin:$PATH ;
     export STACK_YAML=stack-travis.yaml ;
   else
     export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH ;
     case "$DEBIANVER" in
       wheezy)
         export CABAL_CONSTRAINTS='--constraint=transformers==0.3.0.0 --constraint=containers==0.4.2.1 --constraint=bytestring==0.9.2.1 --constraint=text==0.11.2.0 --constraint=time==1.4 --constraint=dlist==0.5 --constraint=convertible==1.0.11.1 --constraint=HDBC==2.3.1.1' ;
         ;;
       '')
         case "$GHCVER" in
           7.[64].*)
              export CABAL_CONSTRAINTS='--constraint=time==1.4'
              ;;
           *)
              ;;
         esac ;
         ;;
       *)
         echo "Unsupported DEBIANVER, $DEBIANVER" ;
         exit 1 ;
         ;;
     esac ;
   fi

install:
 - if [ x"$STACK_RESOLVER" != x ];
   then
     ./travis-CI/stack/install.sh ;
   else
     ./travis-CI/cabal-hvr-ghc/install.sh ;
   fi

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 - if [ x"$STACK_RESOLVER" != x ];
   then
     ./travis-CI/stack/script.sh ;
   else
     ./travis-CI/cabal-hvr-ghc/script.sh ;
   fi
# EOF
