language: haskell
env:
  - GHC_VERSION=7.8
  - GHC_VERSION=7.6
  - GHC_VERSION=platform.2012.2
before_install:
  - date
  - echo $PATH
  - which ghc   ; ghc --version   ; dpkg -l ghc
  - which cabal ; cabal --version ; dpkg -l cabal-install
  - sudo apt-get update
  - find /usr/local/ghc/*/bin -type f -ls
  - case "$GHC_VERSION" in
      platform.2012.2)
        sudo apt-get --purge remove cabal-install ;
        sudo apt-get install haskell-platform haskell-platform-prof haskell-platform-doc cabal-install=0.14.0-2 ;
        export PATH=/usr/bin:$PATH
        ;;

      *)
        export PATH=/usr/local/ghc/$(ghc_find $GHC_VERSION)/bin:$PATH
        ;;
    esac
  - echo $PATH
  - which ghc   ; ghc --version   ; dpkg -l ghc
  - which cabal ; cabal --version ; dpkg -l cabal-install
  - rm /home/travis/.cabal/config ; cabal update
  - cd relational-query
after_script:
  - date
